[tool.poetry]
name = "tests"
version = "1.2.39"
description = "Rysk"
authors = ["jib"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
numpy = "^1.23.3"
eth-abi = "3.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"