name: Clean Stale Preview Apps

on:
  pull_request:
    types:
      # - closed
      - synchronize

jobs:
  Clean:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      VERCEL_PROJECT: ${{ secrets.VERCEL_PROJECT }}
      VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Clean
        shell: bash
        run: |
          deployments=$(
            curl \
            -X GET \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            "https://api.vercel.com/v6/deployments?teamId=$VERCEL_TEAM_ID&projectId=$VERCEL_PROJECT&limit=100&target=preview"
          )
          echo ${{ steps.extract_branch.outputs.branch }}
