name: Hardhat

on:
  push:
    paths:
      - "packages/contracts/**"
      - "package.json"
      - ".github/workflows/hardhat.yml"

defaults:
  run:
    working-directory: ./packages/contracts

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ALCHEMY: ${{ secrets.ALCHEMY }}
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install modules
        run: yarn

      - name: Compile
        run: yarn workspace contracts compile

      - name: Test
        run: yarn workspace contracts test ./test/*.ts
